In [4]:
import pandas as pd
from sqlalchemy import create_engine, text
import os

folder_path = r'C:\Users\abhishek\OneDrive\Documents\Bangalore-B2B-Intelligence-Engine\Data\Processed'

print("Starting the MySQL Intelligence Engine...\n")

user = 'root'                      
password = 'abhiguru46'    
host = 'localhost'                  
db_name = 'b2b_project'             

try:
    engine_base = create_engine(f"mysql+pymysql://{user}:{password}@{host}")
    with engine_base.connect() as conn:
        conn.execute(text(f"CREATE DATABASE IF NOT EXISTS {db_name}"))
    print(f"Database '{db_name}' is ready!")

    engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{db_name}")

    print("Uploading clean data to MySQL tables...")
    df_stores = pd.read_csv(os.path.join(folder_path, 'clean_stores.csv'))
    df_vehicles = pd.read_csv(os.path.join(folder_path, 'clean_vehicles.csv'))

    df_stores.to_sql('stores', con=engine, if_exists='replace', index=False)
    df_vehicles.to_sql('vehicles', con=engine, if_exists='replace', index=False)
    print("Tables 'stores' and 'vehicles' are officially online in MySQL!\n")

    query1 = """
    SELECT 
        MODEL, 
        COUNT(*) as Total_Vehicles
    FROM vehicles
    WHERE LOCATION = 'Yeshwanthpur'
    GROUP BY MODEL
    ORDER BY Total_Vehicles DESC;
    """

    result1 = pd.read_sql(query1, con=engine)
    
    print("--- TARGET LIST: YESHWANTHPUR VEHICLES ---")
    display(result1)
    
except Exception as e:
    print(f"Connection Error: {e}")
    print("Double-check that your MySQL password is correct and your MySQL server is currently running!")

Starting the MySQL Intelligence Engine...

Database 'b2b_project' is ready!
Uploading clean data to MySQL tables...
Tables 'stores' and 'vehicles' are officially online in MySQL!

--- TARGET LIST: YESHWANTHPUR VEHICLES ---

      MODEL  Total_Vehicles
0  Bajaj RE              26

In [7]:
import pandas as pd
from sqlalchemy import create_engine

user = 'root'
password = 'abhiguru46'     
host = 'localhost'
db_name = 'b2b_project'             

try:
    engine = create_engine(f"mysql+pymysql://{user}:{password}@{host}/{db_name}")

    query2 = """
    SELECT 
        APPLICATION as Store_Type, 
        COUNT(*) as Total_Count
    FROM stores
    GROUP BY APPLICATION
    ORDER BY Total_Count DESC;
    """

    result2 = pd.read_sql(query2, con=engine)
    
    print("--- B2B TARGETS: STORE CATEGORY BREAKDOWN ---")
    display(result2.head(10)) # Let's just look at the top 10 most common types
    
except Exception as e:
    print(f"Error: {e}")

--- B2B TARGETS: STORE CATEGORY BREAKDOWN ---

               Store_Type  Total_Count
0           General Store          107
1                  Bakery           77
2                 Medical           70
3               Vegetable           66
4    8 feet road RMC yard           62
5                Clothing           58
6  2nd main road RMC yard           58
7  7nd main road RMC yard           42
8  6nd main road RMC yard           37
9           Grocery Store           28